// <auto-generated />
namespace BlogSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Comment_Field_Rename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Comment_Field_Rename));
        
        string IMigrationMetadata.Id
        {
            get { return "201611241233369_Comment_Field_Rename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
