// <auto-generated />
namespace BlogSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Comments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Comments));
        
        string IMigrationMetadata.Id
        {
            get { return "201611241353087_User_Comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
